server:
  port: 8080
  host: "0.0.0.0"

mysql:
  host: "127.0.0.1"
  port: 3306
  username: "root"
  password: "Szjm270017!"
  database: "onlinechat"
  # host: "117.72.47.192"
  # port: 3306
  # username: "imuser"
  # password: "Im456pwd!"
  # database: "imchat"
  charset: "utf8mb4"
  parseTime: true
  loc: "Local"
  maxOpenConnects: 10
  maxIdleConnects: 5

redis:
  host: "127.0.0.1"
  port: 6379
  password: ""
  db: 0

RabbitMQ:
  Host: "127.0.0.1"
  Port: 5672
  User: "guest"
  Password: "guest"
  VHost: "/"

elasticsearch:
  url: "http://127.0.0.1:9200"
  username: ""
  password: ""

jwt:
  secret: "Rz1n2X7oV8kL9q0uP5hB4wT3yE6iDcSfXzWtYvUaQrKpJmMlNnOoPpQqRrSsTtUuVvWwXxYyZz0123456789-_"
  expireHours: 24
  refreshDays: 7
  issuer: "OnlineChat"

captcha:
  expire_seconds: 120
  length: 5

rate_limit:
  registration_per_minute: 3
  ip_block_minutes: 10

security:
  ipRegisterLimit: 3
  ipRegisterWindow: 60  # seconds
  ipBlockDuration: 86400  # seconds (24 hours)
  captchaExpire: 300  # seconds (5 minutes)

